on:
    pull_request_target:

permissions:
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ 49699333 != github.actor_id }}
        continue-on-error: true
        run: |
          exit 1
          gh pr merge 
      - uses: actions/github-script@v7
        with:
          script: |
            if ( true ) {
              github.rest.pulls.merge(test)
            }
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ 49699333 != github.actor_id }}


