on:
    pull_request:

permissions:
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - run: exit ${{ 49699333 != github.actor_id }}
        if: ${{ always() }}
      - run: exit ${{ github.actor != 'dependabot[bot]' }}
        if: ${{ always() }}
      - run: exit ${{ github.actor_id != '49699333' }}
        if: ${{ always() }}
