on:
    pull_request:

permissions:
  contents: write

jobs:
  auto-merge:
    if: ${{ 49699333 == github.actor }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.head.ref }}
