on:
    pull_request_target:

permissions:
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true
        if: ${{ 49699333 != github.actor_id }}

      - run: exit 0
        continue-on-error: true
        if: ${{ 49699333 == github.actor_id }}
        
      - run: exit 1
        continue-on-error: true
        if: ${{ github.actor_id != '49699333' }}

      - run: exit 1
        continue-on-error: true
        if: ${{ github.actor != 'dependabot[bot]' }}

      - run: exit 1
        continue-on-error: true
        if: ${{ github.actor != dependabot[bot] }}
