on:
    pull_request_target:

permissions:
  contents: write

jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.head.ref }}
