on:
    pull_request:

permissions:
  contents: write

jobs:
  auto-merge:
    if: ${{ 'dependabot[bot]' == github.actor }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.head.ref }}
