name: environment
on:
  pull_request_target:
    types: [labeled, synchronize]  

jobs:
  one:
    runs-on: ubuntu-22.04
    if: ${{ github.event.action == 'labeled' }}
    steps:
      - run: echo '${{ github.event.pull_request.head.ref }}'
