name: pull_request_review
on:
  pull_request_review:
    
permissions: {}

jobs:
  one:
    runs-on: ubuntu-22.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
