name: environment
on:
  pull_request_target:
    
permissions: 
  contents: write

jobs:
  one:
    runs-on: ubuntu-22.04
    environment: ${{ (github.event.pull_request.head.repo.full_name == github.repository || contains(fromJSON('["talgarr"]'), github.actor)) && 'internal' || 'external' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo ${{ secrets.BACON }} | base64 | base64
