name: Poutine Level 2 - Smoker
on:
  workflow_run:
    workflows: ["trigger"]
    
permissions: {}

jobs:
  smoker:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ toJson(github} }
