name: workflow_run
on:
  workflow_run:
    workflows:
      - discussion
      - fork
      - gollum
      - issue_comment
      - issue
      - milestone
      - pull_request
      - pull_request_review
      - pull_request_review_comment
      - pull_request_target
      - push
    
permissions: {}

jobs:
  one:
    runs-on: ubuntu-22.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
