name: workflow_dispatch
on:
  workflow_dispatch:
    inputs:
     sha:  
       type: string
       
permissions: {}

jobs:
  one:
    env:
      FLAG: ${{ secrets.FLAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.sha }}
      - run: bash test.sh
